In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [17]:
sent =['the glass of milk',
       "the glass of juice",
       "I'm good devloper",
       "ArithmeticError is error python "]

In [18]:
voc_size=10000

In [19]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]

In [20]:
one_hot_repr

[[8431, 9403, 3337, 8613],
 [8431, 9403, 3337, 6344],
 [3563, 5502, 9993],
 [6754, 36, 5033, 636]]

In [34]:
## word embedding represtation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
import numpy as np

In [36]:
sent_length=8

In [37]:
embeddings_doc=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)

In [38]:
embeddings_doc

array([[   0,    0,    0,    0, 8431, 9403, 3337, 8613],
       [   0,    0,    0,    0, 8431, 9403, 3337, 6344],
       [   0,    0,    0,    0,    0, 3563, 5502, 9993],
       [   0,    0,    0,    0, 6754,   36, 5033,  636]])

In [39]:
# feature Representation 
dim=10

In [42]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile("adam","mse")

In [43]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
import keras

keras.__version__

'3.4.1'

In [49]:
embeddings_doc[0]

array([   0,    0,    0,    0, 8431, 9403, 3337, 8613])

In [50]:
pred_doc=model.predict(embeddings_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step


In [51]:
len(pred_doc)

4

In [58]:
sent[0]

'the glass of milk'

In [59]:
sent

['the glass of milk',
 'the glass of juice',
 "I'm good devloper",
 'ArithmeticError is error python ']

In [56]:
embeddings_doc[0]

array([   0,    0,    0,    0, 8431, 9403, 3337, 8613])

In [60]:
embeddings_doc

array([[   0,    0,    0,    0, 8431, 9403, 3337, 8613],
       [   0,    0,    0,    0, 8431, 9403, 3337, 6344],
       [   0,    0,    0,    0,    0, 3563, 5502, 9993],
       [   0,    0,    0,    0, 6754,   36, 5033,  636]])

In [55]:
pred_doc[0]

array([[ 0.00589101,  0.03850342, -0.03250541, -0.02663362, -0.00754289,
         0.00706012,  0.00581759,  0.03031403,  0.01228197,  0.04964403],
       [ 0.00589101,  0.03850342, -0.03250541, -0.02663362, -0.00754289,
         0.00706012,  0.00581759,  0.03031403,  0.01228197,  0.04964403],
       [ 0.00589101,  0.03850342, -0.03250541, -0.02663362, -0.00754289,
         0.00706012,  0.00581759,  0.03031403,  0.01228197,  0.04964403],
       [ 0.00589101,  0.03850342, -0.03250541, -0.02663362, -0.00754289,
         0.00706012,  0.00581759,  0.03031403,  0.01228197,  0.04964403],
       [-0.04109045,  0.00975496, -0.02178397, -0.01117885, -0.02531   ,
        -0.03946648,  0.00994272,  0.03632453, -0.00094583,  0.02742891],
       [-0.04872711,  0.0099027 , -0.04765823, -0.03292378, -0.03019834,
         0.02963341,  0.04040593, -0.01623555,  0.02263785, -0.0280681 ],
       [-0.04528517, -0.00966363,  0.03051451,  0.01222254,  0.03352613,
        -0.01335126, -0.0025175 , -0.01226442

In [61]:
pred_doc

array([[[ 0.00589101,  0.03850342, -0.03250541, -0.02663362,
         -0.00754289,  0.00706012,  0.00581759,  0.03031403,
          0.01228197,  0.04964403],
        [ 0.00589101,  0.03850342, -0.03250541, -0.02663362,
         -0.00754289,  0.00706012,  0.00581759,  0.03031403,
          0.01228197,  0.04964403],
        [ 0.00589101,  0.03850342, -0.03250541, -0.02663362,
         -0.00754289,  0.00706012,  0.00581759,  0.03031403,
          0.01228197,  0.04964403],
        [ 0.00589101,  0.03850342, -0.03250541, -0.02663362,
         -0.00754289,  0.00706012,  0.00581759,  0.03031403,
          0.01228197,  0.04964403],
        [-0.04109045,  0.00975496, -0.02178397, -0.01117885,
         -0.02531   , -0.03946648,  0.00994272,  0.03632453,
         -0.00094583,  0.02742891],
        [-0.04872711,  0.0099027 , -0.04765823, -0.03292378,
         -0.03019834,  0.02963341,  0.04040593, -0.01623555,
          0.02263785, -0.0280681 ],
        [-0.04528517, -0.00966363,  0.03051451,  0.0